### ISSUE TITLE
Constantly getting errors when running runMaster.sh

### ISSUE THREAD

**Issue by komalkumaridev** [ucbrise/dory#1]
bench_dir='', bf_sz='1024', max_docs='128', malicious='true'
command-line-arguments
/usr/local/Cellar/go/1.19.1/libexec/pkg/tool/darwin_amd64/link: running clang failed: exit status 1
ld: library not found for -lssl
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Can someone help me with this?

**Comment by edauterman** [comment]
It looks like you haven't installed or properly linked OpenSSL.
