### ISSUE TITLE
Error while trying to execute ./runMaster.sh

### ISSUE THREAD

**Issue by narenkhatwani** [ucbrise/dory#3]
I get the following terminal output after executing ./runMaster.sh

bench_dir='', bf_sz='1024', max_docs='128', malicious='true'
src/master/master.go:20:5: package common is not in GOROOT (/opt/homebrew/Cellar/go/1.20.5/libexec/src/common)

Can anyone please help me resolve this/ tell me what am I doing wrong?

**Comment by edauterman** [comment]
This project was developed using an older version of Go where you had to manually set the `GOPATH` environment variable. If you're using a newer version of Go, you might need a `go.mod` file.

**Comment by karan-gaur** [comment]
Hi. Any chance you can share the version of go with which this was created?
